# Generated by Django 4.0 on 2022-09-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_becomeamembermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(blank=True, null=True)),
                ('established', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SomeFactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.IntegerField(blank=True, default=4, null=True)),
                ('projects', models.IntegerField(blank=True, default=5, null=True)),
                ('participants', models.IntegerField(blank=True, default=450, null=True)),
            ],
        ),
    ]
